export const AGREGAR_PRODUCTO       = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCARGA_PRODUCTOS_EXITO = "DESCARGA_PRODUCTOS_EXITO";
export const DESCARGA_PRODUCTOS_ERROR = "DESCARGA_PRODUCTOS_ERROR";


export const OBTENER_PRODUCTOS_ELIMINAR = "OBTENER_PRODUCTOS_ELIMINAR";
export const PRODUCTOS_ELIMINADO_EXITO = "PRODUCTOS_ELIMINADO_EXITO";
export const PRODUCTOS_ELIMINADO_ERROR = "PRODUCTOS_ELIMINADO_ERROR";


export const OBTENER_PRODUCTOS_EDITAR = "OBTENER_PRODUCTOS_EDITAR";
export const COMENZAR_EDITAR_PRODUCTO = "COMENZAR_EDITAR_PRODUCTO";
export const PRODUCTOS_EDITAR_EXITO = "PRODUCTOS_EDITAR_EXITO";
export const PRODUCTOS_EDITAR_ERROR = "PRODUCTOS_EDITAR_ERROR";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";



